version: '3'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        network_mode: "bridge"
    ws:
        image: ws-proxy:1.0
        environment:
            - VIRTUAL_HOST=ws.localhost
            - WS_CALLBACK_URL=http://api.yumlonne.com
            - CMD=~jetty:start
    api:
        image: ws-chat:1.0
        environment:
            - VIRTUAL_HOST=api.localhost
            - CMD=~jetty:start
    web:
        image: ws-chat:1.0
        environment:
            - VIRTUAL_HOST=localhost
            - CMD=~jetty:start
